### PR TITLE
ci: add deploy to maven as step

### LINKED ISSUE #182: Publish the damap backend package to the public maven repository
**Description**
The damap-backend should be published to the maven repository. https://github.com/tuwien-csd/damap-backend/pull/106 already implemented the github pipeline for this workflow. Now we are missing at least an account. Check what else may be needed and implement it.

### PR DESCRIPTION
**Pull request by rekt-hard**
config: add maven deploy profile

## Description

Feature

Add deploy to maven repository to ci. A profile for maven deployment is declared, as only one `distributionManagement` tag can be set and only one `repository` inside of this can be specified. Deploying to different repositories (github, maven) requires this change.

#### What does this PR do?

Releases will be deployed to maven repository.

#### Dependencies

An account has to be created on https://oss.sonatype.org/ and then the environment variables for the CI have to be set (`OSSRH_USERNAME` , `OSSRH_TOKEN`).

### Checks

- [ ] Tested with Oracle/PostgreSQL
- [ ] Export updated
- [ ] Documentation added
- [ ] Tests added
- [ ] E2e tests created
- [ ] Successfully ran e2e tests before merge

closes #182 

ref #33

### CODE REVIEW

**Comment by rekt-hard** [comment]
We might only want to publish release versions to maven (e.g. v3.0.0) but no snapshots. This will require updating the workflow to only run on tags with a certain naming (e.g. vX.Y.Z) or on manual trigger. Leaning towards tags though

**Review by rekt-hard — COMMENTED** [review]
Thank you for the namespace and refactoring work.

A namespace usually consists of the domain name (e.g. damap.org) and the package (e.g. damap) in reverse (e.g. org.damap.damap) (reference: [oracle docs](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html)). This would result in our package being named `org.damap.damap`.

In a previous resource movement, it was necessary to specify the old file path as an attribute for existing database changeLog files. The root changeLog already has this set, so this is fine. For the v3 changeLog, this has to be adapted. As an example is in the `changeLog-3.0.0_1.yaml` file, an attribute has to be added:
`  - logicalFilePath: at/ac/tuwien/damap/db/changeLog-3.x/changeLog-3.0.0_1.yaml`
Otherwise, liquibase tries to apply the changeLog again, since it treats it as a different changeLog.

**Comment by rekt-hard** [comment]
@larnhold Have the variables for the CI been configured?
If so, merging this PR should result in a `4.0.0-SNAPSHOT` release on OSSRH :)

Otherwise we should wait until everything is configured

**Review by ValentinFutterer — APPROVED** [review]

**Comment by larnhold** [comment]
> @larnhold Have the variables for the CI been configured? If so, merging this PR should result in a `4.0.0-SNAPSHOT` release on OSSRH :)
> 
> Otherwise we should wait until everything is configured

This keys are set in the CI:
OSSRH_USERNAME
OSSRH_TOKEN
GPG_PRIVATE_KEY
GPG_KEY_PASS

If it works is another question - we will see once it is merged :)

**Pull request merged**
