### PR TITLE
conversion: add horizon europe template export

### LINKED ISSUE #47: Horizon Europe template support
Add the Horizon Europe DMP template to the list of supported export templates.
Utilize the funder ID to recognize the funder and utilize this template for the export if it corresponds to the science europe program.

### PR DESCRIPTION
**Pull request by rekt-hard**
## Description

Feature

#### What does this PR do?

Add Horizon Europe template and export functionality

#### Code review focus

Please test the export functionality thoroughly and ensure that no placeholders are left in the exported document.

#### Dependencies

https://github.com/tuwien-csd/damap-frontend/pull/144

### Checks

- [x] Tested with Oracle/PostgreSQL
- [x] Export updated
- [ ] Documentation added
- [ ] Tests added
- [ ] E2e tests created
- [ ] Successfully ran e2e tests before merge

closes #47

### CODE REVIEW

**Comment by rekt-hard** [comment]
Currently unclear what should go into the text in the deliverable abstract at the respective placeholders (marked green)
- [M4]
- [section name]

Need some clarification on this from data steward at TU Wien.

**Review by ZenoLC — CHANGES_REQUESTED** [review]
I found a minor nullpointer issue from a previous changeset and pushed the fix directly, since it was not a part of these changes.

i have the following issues with the template docx itself:
* the comments are not necesary for users, i would remove those.
* the green placeholders might also be superfluous, maybe check in with RDM department on how they prefer it.
* the inserted text has a different font that the existing one. normally it should use the font of the placeholder. maybe there is some hidden formatting somewhere that influences this.

finally i have discovered a new issue, which potentially is not a part of this changeset either:
The list of repositoreies description will insert only one description instead of all of them. This issue persists in other export templates as well. It is not present on stable release though.

In case the last issue is not caused by this changeset, then this PR can be merged regardless and the issue tackled in a separate PR.

**Comment by rekt-hard** [comment]
Thank you for the review, the quick fix and identifying these issues. I will have a look at them this week and add a test case as well.

Also this should probably be the contributor itself instead of the contact: https://github.com/tuwien-csd/damap-backend/pull/118/commits/b05e27ea73f5455fa5bd740b22eec392532ba0b2#diff-5656cd6f95389b86b7d75018850a2becd96cb3aa24c0b071dbcb3b9bce0c9162L285

**Comment by ZenoLC** [comment]
yes, good catch with the contact/contributor bug :)

**Comment by rekt-hard** [comment]
>     * the green placeholders might also be superfluous, maybe check in with RDM department on how they prefer it.
Note sure about the content that should go in here. Please see the comment here: https://github.com/tuwien-csd/damap-backend/pull/118#issuecomment-1803623857

**Review by ZenoLC — APPROVED** [review]
nice work !

**Pull request merged**
