### PR TITLE
refactor ORCID related files

### PR DESCRIPTION
**Pull request by rekt-hard**
refactor/rename ORCID related files

## Description

Bugfix, Refactoring

#### What does this PR do?

Set university ID of ORCID person, as this is also used for front-end logic (e.g. selecting contact person).
Refactor/Rename ORCID related files to match ORCID API. Also eases reading and understanding the code.
Implement fetching a single person from ORCID by its orcid.

#### Breaking changes

none

### Checks

- [ ] Tested with Oracle/PostgreSQL
- [ ] Export updated
- [ ] Documentation added
- [ ] Tests added
- [ ] E2e tests created
- [ ] Successfully ran e2e tests before merge

closes GH-

### CODE REVIEW

**Comment by ZenoLC** [comment]
The universityID is often used in back- and frontend to limit the use of certain contributor objects to functions accessible only by members of the institution running an implementation of damap. Filling it with a non-functional ID, that does not correspond with an institutional ID will cause several issues when trying to gather information from other services with it. E.g. the EDITOR assigning feature will display ORCID users, even though they can not log into the application.

If there are issues that rise from not assigning this ID, then they should be solved differently, as the overhead from having to manage different sets of IDs in the same ID-variable will prove more effort.

**Comment by rekt-hard** [comment]
Thank you for the clarification :)
A possible solution would then be to change the logic in the front-end for selecting the contact person. What would you propose?

**Comment by ZenoLC** [comment]
changing frontend logic sounds like the way to go. i do not have an issue assigning an ORCID contributor as contact person. what is the issue you are experiencing on your end?

**Comment by rekt-hard** [comment]
Discussed via meeting.
Outcome: do not set UniversityID for ORCID contributor, because of reasons mentioned above. Instead, change front-end logic when selecting a contact person (and other places if needed)

**Review by ZenoLC — APPROVED** [review]
good job

**Pull request merged**
